---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - broker
      - zookeeper
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:19092,kafka:29092,kafka:39092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:19092,kafka:29092,kafka:39092 --create --if-not-exists --topic topic --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:19092,kafka:29092,kafka:39092 --create --if-not-exists --topic topic-2 --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:19092,kafka:29092,kafka:39092 --list
      "
  database:
    image: "postgres:12.9-alpine"
    restart: always
    env_file:
      - database.env # configure postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      # copy the sql script to create tables
      - ./init-sql/1-create-dbs.sql:/docker-entrypoint-initdb.d/1-create-dbs.sql
  steeltoe-config:
    #docker run --rm -ti -p 8888:8888 -v $PWD/steeltoe/config-repo:/config --name steeltoe-config steeltoeoss/configserver --spring.profiles.active=native
    image: "steeltoeoss/config-server:latest"
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    ports:
      - "8888:8888"
    #volumes:
    #  - config-data:/config/
    volumes:
      - type: bind
        source: ./config
        target: /config
  eureka-server:
    image: "steeltoeoss/eureka-server:latest"
    ports:
      - "8761:8761"
  spring-boot-admin:
     image: "steeltoeoss/spring-boot-admin:latest"
     ports:
       - "8080:8080"
  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
  ## TODO: 
  # This is broken, looks like docker hub removed?  Would have to download github and build.  Hasnt been maintained since 2016?
  # might look into:
  # https://github.com/Netflix-Skunkworks/hystrix-dashboard
  # Skipping for now.
  # This is still pretty stale? Last commits 4+ years ago
  #hystrix-dashboard:
  #  #https://github.com/kennedyoliveira/standalone-hystrix-dashboard
  #  image: "kennedyoliveira/hystrix-dashboard:latest"
  #  environment:
  #    JVM_ARGS: '-Xmx2048m'
  #  ports:
  #    - "7979:7979"

  #home-service:
  #  image: home-service
  #  ports:
  #    - "8881:8881"
  #  depends_on:
  #    - steeltoe-config
  #    - eureka-server
  #    - database
  #    - kafka-1
  #    - kafka-2
  #    - kafka-3
  #data-import-service:
  #  image: data-import-service
  #  ports:
  #    - "8882:8882"
  #  depends_on:
  #    - steeltoe-config
  #    - eureka-server
  #    - database
  #    - kafka-1
  #    - kafka-2
  #    - kafka-3

volumes:
  database-data: # named volumes can be managed easier using docker-compose
  config-data: