---
version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-1:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-2:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-3:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
    extra_hosts:
      - "moby:127.0.0.1"
  database:
    image: "postgres:12.9-alpine"
    restart: always
    env_file:
      - database.env # configure postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      # copy the sql script to create tables
      - ./init-sql/1-create-dbs.sql:/docker-entrypoint-initdb.d/1-create-dbs.sql
  steeltoe-config:
    #docker run --rm -ti -p 8888:8888 -v $PWD/steeltoe/config-repo:/config --name steeltoe-config steeltoeoss/configserver --spring.profiles.active=native
    image: "steeltoeoss/config-server:latest"
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    ports:
      - "8888:8888"
    volumes:
      - config-data:/config/
    #volumes:
    #  - type: bind
    #    source: ./src/config
    #    target: /config
  eureka-server:
    image: "steeltoeoss/eureka-server:latest"
    ports:
      - "8761:8761"
  spring-boot-admin:
     image: "steeltoeoss/spring-boot-admin:latest"
     ports:
       - "8080:8080"
  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
  ## TODO: 
  # This is broken, looks like docker hub removed?  Would have to download github and build.  Hasnt been maintained since 2016?
  # might look into:
  # https://github.com/Netflix-Skunkworks/hystrix-dashboard
  # Skipping for now.
  # This is still pretty stale? Last commits 4+ years ago
  #hystrix-dashboard:
  #  #https://github.com/kennedyoliveira/standalone-hystrix-dashboard
  #  image: "kennedyoliveira/hystrix-dashboard:latest"
  #  environment:
  #    JVM_ARGS: '-Xmx2048m'
  #  ports:
  #    - "7979:7979"

  #home-service:
  #  image: home-service
  #  depends_on:
  #    - steeltoe-config
  #    - eureka-server
  #    - database
  #    - kafka-1
  #    - kafka-2
  #    - kafka-3
  #data-import-service:
  #  image: data-import-service
  #  depends_on:
  #    - steeltoe-config
  #    - eureka-server
  #    - database
  #    - kafka-1
  #    - kafka-2
  #    - kafka-3

volumes:
  database-data: # named volumes can be managed easier using docker-compose
  config-data: